<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8" isELIgnored="false"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Admin Help Section</title>
<link rel="stylesheet" type="text/css" href="./CSS/admin-help.css">
<style>


</style>
</head>
<body>

	<div class="header">
		<div class="admin-info">
			<div>
				Welcome, <strong>${sessionScope.username}</strong>
			</div>
			<div style="font-size: 0.8rem; opacity: 0.8;">Administrator</div>
			<a href="LoginController?action=logout" class="logout-btn">Logout</a>
		</div>
		<h1>Admin Help Center</h1>
		<p>PAHANA Book Shop Management System</p>
	</div>
	
	<br>
    <a href="LoginController?action=back" class="btn-back"> Back to Dashboard </a>
	
			

		<!-- FAQ Section -->
		<div class="faq-section">
			<div class="faq-header">
				<h2>Click below for help ?</h2>
				<!--<p>Quick answers to common questions</p>-->
			</div>

			<div class="faq-item">
				<div class="faq-question" onclick="toggleFAQ(this)">Customer Management</div>
				<div class="faq-answer">
					<ol>
					<li>Adding a new customer account</li>
						<ul>
							<li>Click on "Add New Customer" Button</li>
							<li>Fill the form required information <b>(account number will be auto generated by the system)</b></li>
							<li>Click on "Add" Customer.</li>
						</ul>
							
					<li>Updating customer information</li>
						<ul>
							<li>Click on "View all customer" Button</li>
							<li>Select the customer you want, click on edit button</li>
							<li>Make the necessary changes required <b>(account number can't be changed)</b></li>
							<li>Click on "Update"</li>
						</ul>
						
					<li>Deleting a customer account</li>
					<ul>
						<li>Click on "delete" button</li>
					</ul>
					</ol>
				</div>
			</div>

			<div class="faq-item">
				<div class="faq-question" onclick="toggleFAQ(this)">Item Management</div>
				<div class="faq-answer">
					<ol>
					<li>Adding a new item to the system</li>
						<ul>
							<li>Click on "Add New Item" Button</li>
							<li>Fill the form required information <b>(item id will be auto generated by the system)</b></li>
							<li>Click on "Add Item"</li>
						</ul>
							
					<li>Updating item information</li>
						<ul>
							<li>Click on "View all items" button</li>
							<li>Select the item you want, click on edit button</li>
							<li>Make the necessary changes required <b>(item id can't be changed)</b></li>
							<li>Click on "Update"</li>
						</ul>
						
					<li>Updating stock quantity</li>
					<ul>
						<li>Click on "View all items" button</li>
						<li>Select the item you want, click on edit button</li>
						<li>Enter the new stock value</li>
						<li>Click on "Update"</li>
					</ul>
					
					<li>Deleting an item</li>
					<ul>
						<li>Click on "View all items" button</li>
						<li>Select the item you want</li>
						<li>Click on "delete"</li>
					</ul>
					</ol>
				</div>
			</div>

			<div class="faq-item">
				<div class="faq-question" onclick="toggleFAQ(this)">Billing Management</div>
				<div class="faq-answer">
					<ol>
					<li>Generating a new bill and print receipt</li>
						<ul>
							<li>Click on "Select customer"</li>
							<li>Select customer from the list</li>
							<li>Click on selected customer</li>
							<li>Go to add items section click on "Select item" and select an item</li>
							<li>Enter the quantity</li>
							<li>Click on "Add Item"</li>
							<li>Item will be added to the list</li>
							<li>If you want add discount you can type the percentage in discount field</li>
							<li>If you want remove a item from the list just click on remove button</li>
							<li>Click on save button, after that click on print receipt button<br><b>Note: Without saving bill you won't be able print receipt</b></li>
						</ul>
							
					<li>View transactions and delete</li>
						<ul>
							<li>Click on "View all bills" button</li>
							<li>If you want to delete a bill just click on "delete"</li>
						</ul>
				</div>
			</div>
		</div>

		<!-- Contact Support -->
		<div class="support-section">
			<div class="support-header">
				
				<h2>Need More Help?</h2>
				<p>Contact our support team for personalized assistance</p>
			</div>

			<div class="support-contacts">
				<div class="support-contact">
					<div class="icon"><img alt="" id="icon_mail" src="./img/mail.png"></div>
					<h3>Email Support</h3>
					<p>admin@pahana.edu.lk</p>
					<p>Response within 24 hours</p>
				</div>			
		</div>
	</div>

	<script>
        function toggleFAQ(element) {
            const answer = element.nextElementSibling;
            const isActive = answer.classList.contains('active');
            
            // Close all other FAQ items
            document.querySelectorAll('.faq-answer').forEach(item => {
                item.classList.remove('active');
            });
            document.querySelectorAll('.faq-question').forEach(item => {
                item.classList.remove('active');
            });
            
            // Toggle current item
            if (!isActive) {
                answer.classList.add('active');
                element.classList.add('active');
            }
        }

        // Search functionality
        document.querySelector('.search-input').addEventListener('input', function() {
            const searchTerm = this.value.toLowerCase();
            const helpTopics = document.querySelectorAll('.help-topic');
            const categories = document.querySelectorAll('.help-category');
            
            categories.forEach(category => {
                let hasVisibleTopics = false;
                const topics = category.querySelectorAll('.help-topic');
                
                topics.forEach(topic => {
                    const text = topic.textContent.toLowerCase();
                    if (text.includes(searchTerm)) {
                        topic.style.display = 'block';
                        hasVisibleTopics = true;
                    } else {
                        topic.style.display = searchTerm ? 'none' : 'block';
                    }
                });
                
                // Hide category if no topics match
                if (searchTerm) {
                    category.style.display = hasVisibleTopics ? 'block' : 'none';
                } else {
                    category.style.display = 'block';
                }
            });
        });

        // Add smooth scrolling for anchor links
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {
            anchor.addEventListener('click', function (e) {
                e.preventDefault();
                const target = document.querySelector(this.getAttribute('href'));
                if (target) {
                    target.scrollIntoView({
                        behavior: 'smooth',
                        block: 'start'
                    });
                }
            });
        });
    </script>
</body>
</html>